stages:
  clean_data:
    cmd: python3 src/data/clean_data.py data/raw/Spb_flats_prices.csv data/interim/cleaned_data.csv
    deps:
      - data/raw/Spb_flats_prices.csv
      - src/data/clean_data.py
    outs:
      - data/interim/cleaned_data.csv


  add_features:
    cmd: python3 src/features/add_features.py data/interim/cleaned_data.csv data/processed/dataset.csv artifacts/unique_values.json
    deps:
      - data/interim/cleaned_data.csv
      - src/features/add_features.py
    outs:
      - data/processed/dataset.csv
      - artifacts/unique_values.json


  prepare_dataset:
    cmd: python3 src/models/prepare_datasets.py data/processed/dataset.csv data/processed/train.csv data/processed/test.csv
    deps:
      - data/processed/dataset.csv
      - src/models/prepare_datasets.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv


  train:
    cmd: python3 src/models/train.py data/processed/train.csv data/processed/test.csv models/model.joblib reports/metrics.json
    deps:
      - data/processed/train.csv
      - data/processed/test.csv
      - src/models/train.py
    outs:
      - models/model.joblib
      - reports/metrics.json